# Default values for elasticsearch-operator-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# platform type e.g. vmware, aws, azure
platform: vmware

# Namespace to associate all objects use by elasticsearch
namespace: elasticsearch

# Name of the cluster role binding used by elasticsearch
es_cluster_role_binding: elasticsearch-operator

# Name of the service account used by elasticsearch
es_service_account: elasticsearch-operator

# Deployment name of the elasticsearch operator
es_deployment: elasticsearch-operator

# Number of elasticsearch opreators should only be 1
es_operator_replicas: 1

# Number of es master nodes
es_master_replicas: 1

# Number of es client nodes
es_client_replicas: 1

# Number of es data nodes
es_data_replicas: 1

# Size of each volume used by es data nodes
volume_size: 10Gi

# network host
network_host: 0.0.0.0

# Location of elasticsearch operator image.
es_operator_image: upmcenterprises/elasticsearch-operator
es_operator_tag: 0.0.8

# pullpolicy for elasticsearch-opreator image
pullPolicy: Always

# Name of the ElasticsearchCluster (third-party resources)
es_cluster_name: example-es-cluster

# Location of elasticsearch image.
es_image: upmcenterprises/docker-elasticsearch-kubernetes
es_tag: 5.3.1

# Location of kibana image.
kibana_image: upmcenterprises/kibana
kibana_tag: 5.3.1

# Name of the Kibana service
kibana_service_name: kibana
# External port number for Kibana
kibana_external_port: 5601

# Location of cerebro image.
cerebro_image: upmcenterprises/cerebro
cerebro_tag: 0.6.8

# Name of the Cerebro service
cerebro_service_name: cerebro
# External port number of Cerebro
cerebro_external_port: 9000

# Java memory settings used by es nodes
java_xms: 256m
java_xmx: 256m

# These settings are specific only to AWS?
# -------------------------------------------------------------------------------------------
# Enable or disable cron scheduler to take snapshot to s3 bucket.
schedule_snapshot: false

# Name of s3 bucket to write snapshots.
# NOTE: s3 bucket must be created manually before deployment
bucket_name: elasticsnapshots99

# Frequency to tell cron to take snapshot
cron_schedule: '@every 2m'

# AWS specific settings
# AWS availabilty zones used by PVC
# NOTE: Must have worker nodes located in each availability zone for PVC to work properly
zones:
 - us-west-2a
 - us-west-2b
 - us-west-2c
storage_type: gp2
# -------------------------------------------------------------------------------------------

# Specify the storage class name of PV that will be uP39S1eNsgx7A4lSffBaHMEMEuqbkw8okpvn3D1Sc2mdVw9WQJ1uSZpQTE9ekj
storage_class: fast

# vmmware = kubernetes.io/vsphere-volume
# aws = kubernetes.io/aws-ebs
# azure = kubernetes.io/azure-disk
storage_class_provisioner: kubernetes.io/vsphere-volume

# Resource provided to Elasticsearch operator
resource_request_mem: 512Mi
resource_request_cpu: 500m
resource_limit_mem: 1024Mi
resource_limit_cpu: 1
