apiVersion: v1
data:
  node-keystore.jks: {{ .Values.keystore }}
  truststore.jks: {{ .Values.truststore }}
kind: Secret
metadata:
  name: es-certs-{{ .Values.es_cluster_name }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
