apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.es_service_account }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
